language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: J1ovhtAl8gIN2w0Zz5eeztJrgykgP3wavi/+yzwMOSwurgJzZrUgX0ukKdpNU3EdLaIce+EmGpGWoHaYO/A2An4yao7Sk4Htn++pNF0oKDEkznQYP185VxmeOwyAP6PAm0CeOLU+nLAvex7ngcCD0SEFUXI/kjnUoNq/7lts1ZSIK3HX80BlAC+SIhtwUdsVgWpH2HLWBJpfaMAqYrtvPkKALP7tkRiXGChp2Y0dxV8yizil8YyEW4jG8GZgLNsksBtE+vUd5G7cB2p5Y6z9DZwGmu5EcnE8yxREKCjTHddm//xjU5njFfP6vqnm3kAPKH6CQpm1e1+tDTRpFyFzDhcjLhbq4Wi3bSywf9K5ute5BjhuOTcktF+0O+uLqgPSTYrLjDtLqD3P0XyI2qmG28kcuoQaT4ZAXV2co73iqTPplRFzFy7Q/Vt6m7jWYVvx20hkDrZ02c0t7+XI+7kRqpq74v97i4SNgsDrhhyzNauB6nyMiO2iWYDhP7xf/aGLCsvjPjLA/RCq/pdybUAOuDMMXay9MNg5tRLLjZIe9VueDZpKxPM5YzIcaIzpYZugCf7AAeYGomv6LzZOQKmsmol2njsr8PFdLhKrRolTTmiTKJZcqquU3BO+IzxWAve8zgxbHRpSK2Cb2VyLLsuSJNnWAQO1ZVj2yKEK2e80Gy4=
  app: intense-sands-31533
