language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: HDp4Ic7KNubwDLAZ5Z5V8ky7cqgExiaDIbsFFSHTQs1Xr1RN0eq7RrPiU3Mer2Gz3U2PCIfQnAP1yHR4bdq5IRO7a+USfX+WktUDqmMN2z5kbFx4HpzW8eYY80TZzTrI2WHQ7fCEGfeGuf+dljox1bn+fz04HgOe7CFdiRXH/tRk6KpXb0I0NmUYmZ+oW3v4RTiTHK/7jI0yCARwGRzb66nI6vZbBrdNe58x6NHAsoPnumB+HiHEyt7ruvPhm6W1GE9AI9HqQQ7HuVJWYbciJ+4X+Ben028ZLpR5fl+0gJykzIPGTclsdpXCyYkAKb01qKyaoklE18M5ZqlnVDyBfhBpAYjYb3AMO4SbIOJwz0uGOqRs4Qh4oOuQHw/BRv91ReGa605UD2+XapEYAFGwjBk9IBVstnb8miFaA5h8s32/eqqpJJpngY7cg2W8R4ClzlD+xCeDE4xnHjyaqXD5KhIcyMQ6EXvlMdxrBN+nfKTZRVtTqmu6r4SuCjmKvMvgyLw71TFUPpKggO40JDlpOuuf1nyYaAtALRBOPx/2Y8ZgBDGWP1cI/cDhGhRzRGnMUF2sJPwGMqt8LUCM2wY3FruE0D+LxloEf0/QBc5b0b33aMPQ+2lurZtR6lxVYcJwAllhCUk8fKFjpvL71cwkPSmkV+lcrgx61Auz/f5C/dA=
  app: intense-sands-31533
  on:
    repo: yugrinkov/carnica-api
  skip_cleanup: 'true'
