language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: PptziDVmgIOK2k44Ts9ivjHuwudl4a8MpPl8ifawv8OGXLovbDWTRGx6vaJpxM5g3uGC3bQnEvxcZ1icVnz0Ur/vUkhVMxCO0fxkrw9RlrRJs6PFOiIRuqrBaabhDci1pdd0Z06vVetuBzhRFij0bgeetZaymkeTXF1FOFaB2h3q9wJVJLkoYmLPhLgJU25LIK5CjjzrV7/BuZlF1kpdrfr/bz12A0NipsdCibX2x/t3TIw9NxTN5d0McT0CtL/CjY/XDqZCjDg6nBbBFkGnl5F0rzhgKTHxzUkCfUSxwLdZjMIT5R7D9QrTHqYA75Fug4eahWRztk50gMjcgkwebYhI6N1uOc4rkUkVWMvj/kS5NFyLQ97hVgqE26Q0sk7gxRuM7w8X0+5y5GIlHvUDMeoaCAsTMRRvm08QlCaKgV7ht7C92BOBxsSg41Qzf8S+EQmkers0rd0szhKhJqb66/4TFW46HWU/QIZY/nObxFsSdZeWTF6Nku1Ocssw0OOhFaMzNYkYyeSxvdTL1MK9WAiVk02/eBIeNN9pBFqbITbrFwLcs9RQEx2thV9BbpVF0glMUcPIBWATf6ExIx/GeS6nvtWG6Xld9ZaJqLRaW60AxzfFdTwxsNxt/iwuBsiZST3+i3MLhVuOko5SyDc1hJ8up+kcXlpSPcmA4oCyyW4=
  app: intense-sands-31533
