language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: FkKrMb/csjp9nD9NF9zypsYeW9CMpqvkoV1ixuppcV9Vjo3ouNcfoULqXJK6j9XppXTXGs00QQO51/9K87PLUJ3GQCYCpWMkjtreuLEG4Zgpm2HeyBBRAurVmkh21TyhzSIXqx7g/x7GnBaDY8mvcShCuddBMBzC7QZESGR5QzN5q6ErJaSNEunW5XCt3K9/9UCNwT8ARMA7bQ5PZ+TUKbRoFLoj1rGhu3pxNP1Jk0lnLyVb7PVeYWfnDut9RBtsnWYyyIHlrAz8IqgpdZ9W1FwJntX8iW3JSlS/EjV24PFS5UcjF3a+PZKDveBvmHRs4yAb+7Araq22Pt1UsZ29/I6VkKEpU5pdWj5oCz/dql34dSJu3vnv+yYukORu0ZPOp0GJIvoZSrqkRbtxY/msYX6txWVwpVQjLqhI+2DLLJwnp0O5I4ugtXHvZ0herObBcbzOzRlyDZzB4+T0H9fDUrgaFsE2nqG1LGorqUEFfBUZOWzNy+MtmM3YfDabWLhxt16ypgplVQDe+2Rjr4l+8cSLDEN5TAVZyAQdTL3b3JWh/fJKz1RvCyURSU1AYp3HofhIZv99ZSLMi/my4C7/ujxyTNXyeJwIsYt6D+wG9n61MX5pgLFJau7x3ILrDx/7pLbKc2n9C/mAM0UOxyyHf7ntqQwffe5U0seZhDLyLjk=
  app: intense-sands-31533
  on:
    repo: yugrinkov/carnica-api
  skip_cleanup: 'true'
