language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ku/8/S4jl5uUIOGG9TqXe9Gnrq/cYycBDagLPyX8S8g7MdntmACr2VvU/NuSM3+DcV5FcoQdePHXS8WeRdAmSRNj12bEH1TjkbCFMTRAFwa9O21vzJe2yQlRUR3u+7o9KRxZX0acT55tzo7flFoJYHDDL0XKq+1HfWPpOObUuYI/s955To6taplc4IVCmKy90LNZ2CCrqPFXA2+JiVdVg1m8kYGIR0G0I3415nkcULKGq54+OY6VnTV7yAQzBrNRuzs8ugtWb32nmpjosz5iDRXem82FO1QgAJohMH0kEdzwdoK7aT6QG5MWLSm3kRuGUJRilPAzACr6f/fCR+8gf7fRBCEx3YSKUlVz+yTXDjdEurxpfgnilBCmSTymda1I1f0BWlB802xoYRGNhyyoSvOsgcx0CKN6f3yqu6tESw7n62E0sqzTat5mbH8OD1wM7FHXlKpSz/rG56UcB0rmLFmvi6z7BPM+6JMVW5WalDoN3/HXo6Go5uGeNm8nL9Nr2bt3JmXKEdplQmlsEZV0Q2psJaXQSUiy+s2VIRpl1YnT6MmgpcbKcjVuwV7MnEy8lWfBufNTWEm8KJcnHnEdM74BpDkqMiqDyrw65B+eol7Lcmc8K6edGItG/AoqXe/aZYukyJxotaTdtugic5agnbarxIYCo0r/OE+/l8jJLVY=
  app: intense-sands-31533
